//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public Cidades()
        {
            this.Fornecedores = new HashSet<Fornecedores>();
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int id { get; set; }
        public int id_Estado { get; set; }
        public string cidade { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual ICollection<Fornecedores> Fornecedores { get; set; }
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
