//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contabilidade
    {
        public int Id { get; set; }
        public Nullable<decimal> caixa { get; set; }
        public Nullable<decimal> banco { get; set; }
        public Nullable<decimal> a_receber_cp { get; set; }
        public Nullable<decimal> a_pagar_cp { get; set; }
        public Nullable<decimal> a_receber_lp { get; set; }
        public Nullable<decimal> a_pagar_lp { get; set; }
        public Nullable<decimal> imposto_recolher { get; set; }
        public Nullable<decimal> moveis_utensilios { get; set; }
        public Nullable<decimal> maquinario { get; set; }
        public Nullable<decimal> veiculos { get; set; }
        public Nullable<decimal> salarios { get; set; }
        public Nullable<decimal> fornecedores { get; set; }
        public Nullable<decimal> clientes { get; set; }
        public Nullable<decimal> outras_entradas_cp { get; set; }
        public Nullable<decimal> outras_saidas_lp { get; set; }
        public Nullable<decimal> empréstimo { get; set; }
        public Nullable<decimal> despesas { get; set; }
        public Nullable<decimal> estoques { get; set; }
        public Nullable<decimal> cap_soc_integ { get; set; }
        public Nullable<decimal> cap_soc_n_integ { get; set; }
        public Nullable<decimal> lucro { get; set; }
        public Nullable<decimal> pro_labore { get; set; }
        public Nullable<decimal> reserva_lucro { get; set; }
    }
}
