//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.Cidades = new HashSet<Cidades>();
        }
    
        public int id { get; set; }
        public string estado { get; set; }
        public string sigla { get; set; }
    
        public virtual ICollection<Cidades> Cidades { get; set; }
    }
}
