//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int id { get; set; }
        public int id_produto { get; set; }
        public int qnt_atual { get; set; }
        public int qnt_minima { get; set; }
        public Nullable<int> qnt_maxima { get; set; }
        public Nullable<int> num_local { get; set; }
        public string letra_local { get; set; }
        public string ref_local { get; set; }
    
        public virtual Produtos Produtos { get; set; }
    }
}
