//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentos
    {
        public Movimentos()
        {
            this.Pagamentos = new HashSet<Pagamentos>();
        }
    
        public int id { get; set; }
        public string desc { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> id_tipo { get; set; }
    
        public virtual Tipos_Movimentacao Tipos_Movimentacao { get; set; }
        public virtual ICollection<Pagamentos> Pagamentos { get; set; }
    }
}
