//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamentos
    {
        public Pagamentos()
        {
            this.Vendas = new HashSet<Vendas>();
        }
    
        public int id { get; set; }
        public string tipoPag { get; set; }
        public string formaPag { get; set; }
        public int qntParcelas { get; set; }
        public int numParcela { get; set; }
        public decimal valorParcela { get; set; }
        public string numChequePrimeiro { get; set; }
        public string numChequeUltimo { get; set; }
    
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}
