//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamentos
    {
        public int id { get; set; }
        public string tipoPag { get; set; }
        public string formaPag { get; set; }
        public Nullable<decimal> valorTotal { get; set; }
        public Nullable<int> qntParcelas { get; set; }
        public Nullable<System.DateTime> dataPagamento { get; set; }
        public Nullable<int> numParcela { get; set; }
        public Nullable<decimal> valorParcela { get; set; }
        public string numChequePrimeiro { get; set; }
        public string numChequeUltimo { get; set; }
        public Nullable<int> id_venda { get; set; }
    
        public virtual Vendas Vendas { get; set; }
    }
}
