//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public Produtos()
        {
            this.Vendas_Produtos = new HashSet<Vendas_Produtos>();
        }
    
        public int id { get; set; }
        public string cod_produto { get; set; }
        public string desc_produto { get; set; }
        public string und_medida { get; set; }
        public double preco_compra { get; set; }
        public double preco_venda { get; set; }
        public byte[] imagem { get; set; }
        public int qnt_estoque { get; set; }
        public int id_fornecedor { get; set; }
        public int status { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual ICollection<Vendas_Produtos> Vendas_Produtos { get; set; }
    }
}
