//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_Movimentacao
    {
        public Tipos_Movimentacao()
        {
            this.Movimentos = new HashSet<Movimentos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string direcao { get; set; }
        public string sub_tipo { get; set; }
        public string conta { get; set; }
        public string forma_pag { get; set; }
        public Nullable<bool> mostrar { get; set; }
    
        public virtual ICollection<Movimentos> Movimentos { get; set; }
    }
}
