//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoja1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public Vendas()
        {
            this.Vendas_Produtos = new HashSet<Vendas_Produtos>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> data_Venda { get; set; }
        public string cfp { get; set; }
        public string cnpj { get; set; }
        public Nullable<int> produtos_Id { get; set; }
        public Nullable<double> valor_Venda { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public int id_Cliente { get; set; }
        public int desconto { get; set; }
        public int comissao { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Vendas_Produtos> Vendas_Produtos { get; set; }
    }
}
